import { Inter } from 'next/font/google'

import '@/assets/styles/globals.scss'
import React from 'react'
import { Metadata } from 'next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Kostya Cinema',
	description: 'Generated by create next app'
}
export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>{children}</body>
		</html>
	)
}
